name: Deploy TIL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'

    - name: Install packages
      run: yarn install

    - name: Build static pages
      run: yarn build

    - name: Publish onto gh-pages
      run: npx gh-pages -d build
